### PR TITLE
test(mix): add new test for 'mix' functionality

### PR DESCRIPTION
**Pull request by ZuBB**

### CODE REVIEW

**Comment by ZuBB** [comment]
@iamstarkov this used to work

2015-06-22-233419_1920x1080_scrot

**Comment by iamstarkov** [comment]
Can you change test for rgb instead of rgbArray?

**Comment by iamstarkov** [comment]
btw, If I will run `a { color: mix(cyan, yellow, 0.3); }` it will get me `a { color: #feff01; }` and google chrome suggests me that `#feff01` is `rgb(254, 255, 1);` so behavior is correct and expected value is not

**Comment by ZuBB** [comment]
http://www.w3schools.com/tags/ref_colormixer.asp?colorbottom=F0F8FF&colortop=FFFFFF

pay attention to `#4CFFB2` that is close to (77, 255, 179)

**Comment by iamstarkov** [comment]
I’m not sure that w3schools is using the same algorhytm

**Comment by ZuBB** [comment]
yea, its might use another algorithm. but my point is different

I put 2 colors `#00FFFF` (cyan) and `#FFFF00` (yellow) and weight 0.3 and I get (almost) what I expect. New algorithm does not do that

**Comment by iamstarkov** [comment]
result is not only 0.X of first color, but also (1–0.X) of second color

**Comment by ZuBB** [comment]
yes, that's true. but forget a bit about new algorithm and code behind it

try to think as absolutely lazy dev (like me).

lib that I am using was updated because it got fixed version of some method. tests for it were ported from other software. OK, sounds good. Lets try to use it

case \#1: I have used new version of `mix()` method in "test case" for #46. Using new version of `mix()` method and uncommented code did not help (see last image in that issue): every cell become black. since I (or we) do not sure what method is buggy I made a new test and left only new version of `mix()` method. cells stop to be black but without proper coloring. 1:0, old code of `mix()` method wins
case \#2: I have used an example provided in project's readme (case with 'cyan' and yellow). I would say here are 2 points:
* after mixing those two colors (cyan - `#00FFFF` and yellow - `#FFFF00`) new algorithm returns next value `#FEFF01` which is incredibly close to 2nd color, however 'weight' param is more close to 1th color.
* lets move prev example into visual space. Result color will be between those 2 colors. Because of weight that is not really small that color should not be too close to any of parent points(colors). while in your case it does (weight - 0.3, #FFFF00 - 2nd color, `#FEFF01` - result).  

due to this I would say that backward compatibility has been broken with new code.

I am lazy and do not want to move to new version which is buggy to me. Thanks to God of JS I am using static build (reasons does not matter here) of this lib and I can stay with it.

Its up to @MoOx and @harthur to decide if this is a regression or not. 

Hope my points are clear.

**Comment by iamstarkov** [comment]
I will tell few words too. To be honest SASS is not rare "other" software, it is very popular product, so as far as I understand it has production-ready version of mix. My motivation was to to replace original noname-version implementations with widely approved one (by sass-consumers).

> after mixing those two colors (cyan - #00FFFF and yellow - #FFFF00) new algorithm returns next value #FEFF01 which is incredibly close to 2nd color, however 'weight' param is more close to 1th color.

It’s very unobvious how weight is used anyway, like `color1*w` and `color2*(1-w)` or inverted combination. I’m still not sure what is better, that’s I took most prevalent implementation.

Second is not clear for me, because if we are mixing two colors in proportions `color1 * 0.3 + color2 * 0.7`, then it is normal for result to be more like second color.

**Comment by iamstarkov** [comment]
> due to this I would say that backward compatibility has been broken with new code.

due semver it’s technically allowed to change API under 1.x, but I _did_ get your point. Sorry about broken compatibility, [I didn’t want to do it](https://github.com/harthur/color/pull/60#issuecomment-113559256).

> I am lazy and do not want to move to new version which is buggy to me. Thanks to God of JS I am using static build (reasons does not matter here) of this lib and I can stay with it.

\0/ ave npm! You can use freeze on prev package’s version you are using in your project, like this: `"color": "0.8"

**Comment by ZuBB** [comment]
I have found why new algorithm does not work for me. next thing used to work before change
```
Color('cyan').mix(Color('yellow'), 0.3)
```
To get same result now we need to do next
```
Color('cyan').mix(Color('yellow'), 30)
```

I see two issues here:
* that change is not reflected in readme
* all API calls of this lib uses decimal numbers (0..1) as percents while in `mix()` we use int numbers. this makes whole API a bit inconsistent..

**Comment by MoOx** [comment]
I guess we should do something about the 0..1/0..100 change somewhere ?
Does a change to the README will make you both happy ?
I do not use mix() at all so, it's not an issue for me :/

**Comment by ZuBB** [comment]
one more question popped out in my mind: what do we fix in 1a82d1ef, since it works as it used to be?

**Comment by ZuBB** [comment]
@MoOx if you are ok with fact that 1 API call will be use another type of number as percent value then updating readme should be OK.

as a regular user I would like to see single type of number is used for passing percent value (and no additional actions should be done on update). however I am not a regular user, I am forced to stick with some changeset between 0.6 and 0.7. 

Btw since #60 updates a `mix()` implementation I am sure it will not solve #46, so we need to reopen it

sorry for making a buzz on all this stuff..

**Comment by iamstarkov** [comment]
Sorry about inconsistent API. Opposite to @MoOx I didn’t use other methods in this lib. From my perspective appeared inconsistent is my fault and we shouldn’t update readme. It’s better to update weight handling

**Comment by ZuBB** [comment]
@iamstarkov :+1: 

Hope @MoOx is OK with your suggestion

**Comment by MoOx** [comment]
PR seems good to get everything in a 0..1 range. What should we do with this PR ?

**Comment by iamstarkov** [comment]
I will create PR to get everything to 0..1 range and after fix. this pr can be closed

**Comment by MoOx** [comment]
Ok good to heard :) Thanks !

**Pull request closed without merging**
