### PR TITLE
fix mix percentage

### PR DESCRIPTION
**Pull request by iamstarkov**
fixing the range from 0..100 to 0..1
/cc @michaeljones @ZuBB

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks

**Comment by ZuBB** [comment]
@MoOx maybe we need to do make a new release (0.9.1 or 0.10.0)?

**Comment by MoOx** [comment]
0.10.0 released

**Comment by michaeljones** [comment]
Great to see! Though I have a little feedback, as mentioned in the other thread, we're now multiplying by 100 only to divide by 100 in the next line. Seems unnecessary!

**Comment by iamstarkov** [comment]
le sigh(

**Comment by iamstarkov** [comment]
at least it fixed and methods are consistent again

**Pull request merged**
